        Mstab = zeros(Nm);
        for ii = 1:Nm
            for jj = 1:Nm
                % Mstab(ii, jj) = integral_robin_P2(node, elem, bdFlag, ...
                %                                 extend_mid(EI(:,ii)), ...
                %                                 extend_mid(EI(:,jj)), [], option);
                Mstab(ii, jj) = integral_robin_penal(node, elem, bdFlag, ...
                                                     extend_mid(EI(:,ii)), ...
                                                     extend_mid(EI(:,jj)), option);
            end
        end
